name: Tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set npm token
        uses: actions/setup-node@v2
        with:
          registry-url: https://<%= registryUrl %>
        env:
          NODE_AUTH_TOKEN: ${{ secrets.<%= githubNodeAuthTokenName %> }}

      - name: Install
        run: yarn boot

      - name: Build
        run: yarn build
      
      - name: Run tests
        run: yarn test